version: '3.9'

services:
  db:
    hostname: db
    image: ankane/pgvector
    ports:
      - ${DATABASE_PORT}:5432
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # init script
      - ./data:/var/lib/postgresql/data # persist data
